#!/usr/bin/env luajit
--[==[
Collect every translatable string and write l10n/TEMPLATE.lua.

    luajit tools/extract-strings.lua          # rewrite the template
    luajit tools/extract-strings.lua --check  # fail if it is out of date (CI)

Matches `_("...")` and `_([[...]])`, which is every form Reddle uses. It is a
scanner rather than a parser, so a string built by concatenation will not be
found -- keep the whole sentence inside the call, which is what a translator
needs anyway.
--]==]

local root = arg[0]:match("(.*)/tools/extract%-strings%.lua") or "."

local function sources()
    local out = {}
    local pipe = io.popen("ls " .. root .. "/*.lua")
    for line in pipe:lines() do
        -- The catalogue itself holds translations, not sources.
        if not line:match("reddle_gettext%.lua$") then out[#out + 1] = line end
    end
    pipe:close()
    table.sort(out)
    return out
end

local seen, order = {}, {}
local function add(s, file)
    if s == "" or seen[s] then return end
    seen[s] = file:match("[^/]+$")
    order[#order + 1] = s
end

for _i, path in ipairs(sources()) do
    local f = io.open(path, "r")
    local body = f:read("*a")
    f:close()
    -- A quoted literal has to be interpreted, not copied: the source says \n,
    -- the string the code looks up at runtime holds a newline, and a key with
    -- the backslash still in it can never match. Long-bracket strings process no
    -- escapes, so those are taken verbatim.
    for lit in body:gmatch('_%(%s*("[^"]*")') do
        local ok, value = pcall(load("return " .. lit))
        add(ok and value or lit:sub(2, -2), path)
    end
    for lit in body:gmatch("_%(%s*%[%[(.-)%]%]") do add(lit, path) end
end

table.sort(order)

local out = {
    "--[[",
    "Every translatable string in Reddle, generated by tools/extract-strings.lua.",
    "",
    "To translate: copy this to l10n/<code>.lua, where <code> is KOReader's",
    "language code (de, fr, pt_BR, zh_CN), and fill in the right-hand sides.",
    "Leave a value empty and the English is used, so a partial translation is",
    "perfectly usable -- send one in at any stage.",
    "",
    "%1 and %2 are substituted at runtime; keep them, in whatever order the",
    "sentence needs. Do not translate the reddle: URLs or the CSS.",
    "--]]",
    "",
    "return {",
}
for _i, s in ipairs(order) do
    local key = string.format("%q", s):gsub("\\\n", "\\n")
    out[#out + 1] = string.format("    [%s] = %s,", key, '""')
end
out[#out + 1] = "}"
local body = table.concat(out, "\n") .. "\n"

local target = root .. "/l10n/TEMPLATE.lua"
if arg[1] == "--check" then
    local f = io.open(target, "r")
    local have = f and f:read("*a")
    if f then f:close() end
    if have ~= body then
        io.stderr:write("l10n/TEMPLATE.lua is out of date -- run:\n",
            "  luajit tools/extract-strings.lua\n")
        os.exit(1)
    end
    io.write(#order, " strings, template up to date\n")
    os.exit(0)
end

os.execute("mkdir -p " .. root .. "/l10n")
local f = assert(io.open(target, "w"))
f:write(body)
f:close()
io.write("wrote ", target, " (", #order, " strings)\n")
